# Generated by Django 4.2.1 on 2023-05-07 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bigNose', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='word',
            name='count',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='word',
            name='img',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='word',
            name='transcription',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='wordscategories',
            name='progress',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
